import = ["~/.config/alacritty/solarized_dark.toml"]

[window]
title = "Terminal"

[scrolling]
history = 10000
multiplier = 1

[font]
normal = { family = "Jetbrains Mono", style = "Regular" }
size = 10

[mouse]
hide_when_typing = true
