[window]
title = "Terminal"

[scrolling]
history = 10000
multiplier = 1

[font]
normal = { family = "monospace", style = "Regular" }
size = 11

[colors]
[colors.primary]
foreground = "#d8d8d8"
background = "#181818"

[mouse]
hide_when_typing = true
